services:

  # Ferramenta para gerenciar banco de dados
  adminer:
    image: adminer:latest
    container_name: foodcore-adminer
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - fastfood-network
    restart: unless-stopped

  # Azure Service Bus Emulator
  azure-service-bus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: foodcore-azure-service-bus-emulator
    restart: unless-stopped
    volumes:
      - "./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    depends_on:
      - azure-service-bus-emulator-sql-server
    ports:
      - "${AZ_SVC_BUS_PORT}:5672"
      - "${AZ_SVC_BUS_MGMT_PORT}:5300"
    networks:
      - fastfood-network
    env_file:
      - .env
      
  azure-service-bus-emulator-sql-server:
    container_name: "foodcore-azure-service-bus-emulator-sql-server"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      fastfood-network:
        aliases:
          - "${SQL_SERVER}"
    env_file:
      - .env
    volumes:
    - az_svc_bus_sql_data:/var/opt/mssql
    
  zipkin:
    image: openzipkin/zipkin
    container_name: foodcore-zipkin
    ports:
      - "${ZIPKIN_PORT}:${ZIPKIN_PORT}"
    env_file:
      - .env
    environment:
      - SERVER_PORT=${ZIPKIN_PORT}
    networks:
      - fastfood-network
    restart: unless-stopped

networks:
  fastfood-network:
    driver: bridge

volumes:
  az_svc_bus_sql_data: