name: CD Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v7
        with:
          name: tfplan
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ci.yml

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
