name: Destroy Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      TF_VAR_location: ${{secrets.AZURE_REGION}}
      TF_VAR_aws_location: ${{secrets.AWS_REGION}}
      TF_VAR_default_customer_password: ${{secrets.DEFAULT_CUSTOMER_PASSWORD}}

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan
      
      - name: Terraform Destroy with Plan
        run: terraform apply -destroy -auto-approve tfplan 